apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: "{{ networkid }}"
spec:
  config: '{
            "name": "{{ networkid }}",
            "type": "bridge",
            "bridge": "br-{{ networkid }}",
            "isDefaultGateway": true,
            "forceAddress": false,
            "ipMasq": true,
            "hairpinMode": true,
            "ipam": {
              "type": "host-local",
              "subnet": "{{ subnet }}",
              "rangeStart": "{{ startip }}",
              "rangeEnd": "{{ endip }}"
            }
        }'