pipeline{
    agent any
    stages{
        stage('onboard chaos-monkey-docker'){
            steps{
				sh "lmctl env list"
				sh "lmctl project push testing"               
            }
        }
        stage('test chaos-monkey-docker'){
            steps{
                sh "lmctl project test testing"
            }
        }
        stage('package chaos-monkey-docker'){
            steps{
                sh "curl -v -u admin:admin123 --upload-file ./_lmctl/_build/chaos-monkey-docker-1.0.tgz http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/chaos-monkey-docker/"              
            }
        }
    }
}