---

- name: template the network descriptor
  template:
    src: multus-network.yaml
    dest: "/opt/{{ networkid }}.yaml"

- name: Create multus network CRD
  command: "kubectl apply -f /opt/{{ networkid }}.yaml"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
