---
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: Remove from Dispatch List
  hosts: "{{ instance_name }}"
  gather_facts: False
  become: true

  vars:
    host_ip: "{{ ipaddr }}"
    host_port: "{{ port }}"
    dispatch_list_template: "{{ lookup('file', 'config/dispatcher.list.template') }}"
    lock_file_path: "/tmp/kamailio.lock"
    
  pre_tasks:      
   - wait_for:
       path: "{{ lock_file_path }}"
       state: absent  
      
   - name: create lock file 
     file:
       path: "{{ lock_file_path }}" 
       state: touch
       
  post_tasks:
   - name: delete lock file 
     file: 
       path: "{{ lock_file_path }}" 
       state: absent
           
  tasks:
    - name: update dispatch list
      block:
        - name: remove entry from dispatch list file
          lineinfile:
            path: /usr/local/etc/kamailio/dispatcher.list
            line: "1 sip:{{ host_ip }}:{{ host_port }}"
            state: absent

        - name: reload dispatch list
          shell: /usr/local/sbin/kamcmd dispatcher.reload
      always:
        - name: delete lock file 
          file: 
            path: "{{ lock_file_path }}" 
            state: absent      