---

- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: Include Kubernetes Install
  when: type == "Kubernetes"
  import_playbook: Install-Kubernetes.yml

- name: Include Openstack Install
  when: type == "Openstack"
  import_playbook: Install-Openstack.yml
