---
- name: get deployment location_server
  hosts: localhost
  gather_facts: False
  roles:
    - { role: get_instance }

- name: Start Lifecycle Transition
  hosts: "{{ mgmt_ip }}"
  gather_facts: False
  become: true

  tasks:
  - name: Report integrity
    debug:
      msg: 
        - "Kamailio is OK"
   
