---
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: Start Lifecycle Transition
  hosts: "{{ instance_name }}"
  gather_facts: False
  become: true

  tasks:
  - name: Report integrity
    debug:
      msg: 
        - "Kamailio is OK"
   
