---
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: Include Kubernetes Uninstall
  when: type == "Kubernetes"
  import_playbook: Uninstall_Openstack.yaml

- name: Include Openstack Uninstall
  when: type == "Openstack"
  import_playbook: Uninstall_Openstack.yaml
