---
- name: get deployment location_server
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: Install Lifecycle Transition
  hosts: "{{ 'localhost' if vimtype=='openstack' else 'dockerlocation' }}"
  gather_facts: False
  become: true
    
  roles:
    - { role: delete_instance }