---
- name: get deployment location_server
  hosts: localhost
  gather_facts: False
  become: true
  roles:
    - { role: get_instance }

- name: create instance
  hosts: "{{ location_server }}"
  gather_facts: False
  become: true
    
  roles:
    - { role: delete_instance }