---
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }


- name: Integrity Lifecycle Transition
  hosts: "{{ instance_name }}"
  gather_facts: False
  become: true

  tasks:
  - name: Check if Asterisk is running
    shell: "ps aux"
    register: asterisk_status

  - name: Report status of Asterisk
    fail:
      msg: Asterisk is not running.
    when: asterisk_status.stdout.find('asterisk') == -1


