- name: Find image
  os_image_facts:
    image: "{{ imagename }}"
  register: sipp_image
  failed_when: sipp_image['ansible_facts']['openstack_image']['id'] is not defined
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: Show image id
  debug:
    var: sipp_image['ansible_facts']['openstack_image']['id']

- name: create sipp security group
  os_security_group:
    state: present
    name: "sipp-{{ instance_name }}"
    description: "security group for sipp {{ instance_name }}"
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: open ssh ports 
  os_security_group_rule:
    security_group: "sipp-{{ instance_name }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: create mgmt port
  os_port:
    state: present
    name: "mgmt_port-{{ instance_name }}"
    network: "{{ mgmt_network }}"
  register: mgmt_port_result
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- debug:
    var: mgmt_port_result

- name: create data port
  os_port:
    state: present
    name: "data_port-{{ instance_name }}"
    network: "{{ data_network }}"
  register: data_port_result
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- debug:
    var: data_port_result

- name: Start SIPP virtual machine
  os_server:
    state: present
    name: "{{ instance_name }}"
    image: "{{ sipp_image['ansible_facts']['openstack_image']['id'] }}"
    timeout: 200
    auto_ip: false
    security_groups: "sipp-{{ instance_name }}"
    flavor: m1.small
    key_name: "{{ keyname }}"
    userdata: "{{ lookup('file','../../config/sipp-user-data.yml') | string}}"
    nics: "port-id={{ mgmt_port_result['id'] }},port-id={{ data_port_result['id'] }}"
  register: server_result
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- debug: 
    var: server_result

- name: check ssh is working on ip pbx vm before proceeding
  delegate_to: jumphost
  wait_for:
    port: 22
    host: "{{ mgmt_port_result['port']['fixed_ips'][0]['ip_address'] }}"
    timeout: 60

- name: report PROPERTIES
  debug:
    msg:
    - "mgmt_address: {{ mgmt_port_result['port']['fixed_ips'][0]['ip_address'] }}"
    - "data_address: {{ data_port_result['port']['fixed_ips'][0]['ip_address'] }}"
