---
ansible_user: ubuntu
ansible_host: {{ properties.mgmt_ip_address }}
ansible_ssh_pass: ubuntu
ansible_connection: ssh
ansible_become_pass: ubuntu
ansible_sudo_pass: ubuntu
ssh_with_jumphost: "-o 'UserKnownHostsFile=/dev/null' -o StrictHostKeyChecking=no -o ProxyCommand='sshpass -p {{ properties.jumphost_password }} ssh -o 'UserKnownHostsFile=/dev/null' -o StrictHostKeyChecking=no -W %h:%p {{ properties.jumphost_username }}@{{ properties.jumphost_ip }}'"
ssh_without_jumphost: "-o 'UserKnownHostsFile=/dev/null' -o StrictHostKeyChecking=no"
ansible_ssh_common_args: "{{ ssh_with_jumphost if properties.jumphost_ip is defined else ssh_without_jumphost }}"