---
- name: "Remove ip pbx instance {{ instance_name }}"
  os_server:
    state: absent
    name: "{{ instance_name }}"
  register: server_result
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: "remove voip security group ippbx-{{ instance_name }}"
  os_security_group:
    state: absent
    name: "ippbx-{{ instance_name }}"
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: remove data port
  os_port:
    state: absent
    name: "data_port-{{ instance_name }}"
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: remove mgmt port
  os_port:
    state: absent
    name: "mgmt_port-{{ instance_name }}"
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   
    
