- name: work out bridge name
  set_fact:
    bridgeName: "{{ networkname }}"

- name: Create a network with options
  docker_network:
    name: "{{ networkname }}"
    driver_options:
      com.docker.network.bridge.name: "{{ bridgeName }}"
    ipam_options:
      subnet: "{{ subnet }}"
      gateway: "{{ gateway }}"
      iprange: "{{ iprange  }}"
  register: net_result

- set_fact:
    id: "{{ ansible_facts.docker_network.Id}}"

- name: report INTERNAL_RESOURCE
  debug:
    msg:
     - "name: {{ bridgeName }}"
     - "id: {{ id}}"
     - "type: docker-network"

- name: report PROPERTIES
  debug:
    msg:
      - "networkid: {{ id }}"
      - "bridgeid: {{ bridgeName }}"
