---


- name: Start Integrity Transition
  hosts: resource
  gather_facts: False
  become: true
  tasks:
  - name: Check if sipp is running
    shell: ps aux | grep sipp | grep -v grep
    ignore_errors: yes
    changed_when: false
    register: sipp_status

  - name: Report status of SIPP
    fail:
      msg: |
        SIPP is not running.
        Return code from `grep`:
        {{ sipp_status.rc }}
    when: sipp_status.rc != 0