---

- name: Install Lifecycle Transition
  hosts: resource
  gather_facts: False
  # become: true

  tasks:
  - name: pause
    shell: python --version

  - name: input key
    debug:
      msg: "echo {{ properties.input_key }}"

  - name: input key path
    debug:
      # note: any key property private keys are written to the file system at a path given
      # by [LM property name]_path
      msg: "echo {{ properties.input_key_path }}"

  - name: input key name
    debug:
      # note: a key property name is given by [LM property name]_name
      msg: "echo {{ properties.input_key_name }}"

  - name: Report PROPERTIES
    set_fact:
      output__infrastructure_id: "{{ system_properties.infrastructureId }}"
      output__input_key_as_string: "{{ properties.input_key }}"
      output__input_key_path: "{{ properties.input_key_path }}"
      output__input_key_name: "{{ properties.input_key_name }}"
      # an output key is persisted by Brent and the key name (currently a UUID generated by
      # Brent) is returned to LM. Notice that the key consists of both a private
      # and public RSA key pair, each enclosed in marker strings.
      # output__output_key: "reskey1#-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA082mUS0aYdCnRGOU2BKN0rYUwWdK8w2I7m7IiiMBB0PQqfW/\njYNrRWDUbQAPRsDaVI112Vj3pIyw1e9mr4MrB8bAkSKvRjloj61v9S2a3KPJ+tmg\n0vs457E85Cm5Y6e2OYb1e12VRHU19Pdx6TPFEpi9iJ0CQdo8/zBL40orvlcLGFe5\nN4sbgPcLcpJ7tOSA34vJh4EGH69Li4kG2HNT4B/Cj4wMgrB4wWXENpGUT44EQ5VX\nS4XNIbnbe4QLlS4/LwKRMSEKlwSjzifxPjrseDvYjeU3hfo7ZHXGOXBau3fLBAr1\n08pj4RwLuA0+yFUNs20u6dctz5ccSJ8seKt3zwIDAQABAoIBAB0tQzADipLW73PY\nU/S/+ZGBS7KozAZXYvmVgUKmN8oMaX5AQDb6V5ijEiBB1djlUC49nnJmcxbT2rhd\n1kNvSkoz8usLYCHIXsMMHVQlCCRE29oWiLUHrnscS0sTBFraC5w5Hy/zYFCh5ODu\nBV8eppM9Pz7Ggj0YFzcALDQPT59UlgspkpedL+TQG3q3MtbjcPruSPGW2zcjluix\nk6Juq0KK9lIplhCqeTzcAc22aF0hkA+Uy0mSU3ezu3oEqMCTshRUNeOoLM+1uqaq\nMiXuR2+GM40raUTpqPHBRIcA0MgmQKNLHeZlHryA/tDlmgZqI6Zqj6Dbr1maHDbw\n0nUDV6ECgYEA9tcqazV/+QiMxLgutzshAQT3Veel9DEKS4GscVi/3RA+LRV3RG9x\nh7pBXsy/8T3xAgskSG4P35+sAxfHeigzHgzZ2+1BA3r6T3kH/CNB4ms5BFHLPdDR\nCcfmOw0eufzCbF1pJhrMz3lGMcc66LLbe82L01b4pWyp3nIlv+Cpr9MCgYEA26mm\n9brRpGYKT37EBWivbUxdq8X44MM8l1bdB0OFQI+BmhhsyvXaganfIaZhvbyaesI6\niGO1wasi9zEIJNfQhQ9hBHCBiBOwM/7I0vX78xZ+COG7Mkwo6g6aeywq17qKBONS\nREfR/hJSEiVTVLjqXoAwW10DDLeAE0YOFaiEFpUCgYATt55A0BY321H7SMcahdOe\nFDp5lzZvahdrbqFKsI8q5mhBC6zqP4ivEda07uAKMit1QVSVoI0ODOAdoyGhBWMH\n7Hjek3YVBBbIkF9t6ZcSsgPs72evuWVpRZmDcAnbS3BwXYnPrGZd0E8mHMb83YSg\nwAuCRzk3ZZWwGigfyp9jVwKBgHRkcqlmMktwHip9OxS6oanCeyfXoMZH7UUrq7Z7\nmpHY+I1UP+FTYFKwViEYblYBJ8HARQ+b9eUG72IXwv7ys/Stb3TQwHIALK+AY50U\n5kmqM2I1aeF+5XcQAd8eSh1BJHzujtrLS4Pa5U3kJUGRMe6c8gKXSFRmryCHUFM9\nla/5AoGBALll68ieXAOArEjwl430Kn/OhB3ooNXyaU2Fwd483hSXhyFCE7eZT74s\nfk+oUfWwzYikgUdysVH0WxQrCwEvdyspkY9tdaBBlDmnLE667+loEyLB5He+cLdb\nqM1WW846OQdtK5Vn7H0dH1aCeVu57Yh/YDUkzyC94r4u8yK0DU6w\n-----END RSA PRIVATE KEY-----=#ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJ1t35uQorDiR8gmXQtbGB6W+NrK4nx+IYj8bTBsQu0gx4jlYNwb2wzaeejLU7QP8FB5G3eclo7emUNK479Eg/UMtPmNzsQhRjlUKonuYLPncLGKtetFgjMnmePvi8mudl9o1alvcdtn41VofNZ4dN8RcgKIJOdS1Xd4vwHEW57PhUNIHs0x2MHfPQ0wsz1vzUrof4B2bxFkXI4f3kTXKV2n3MMfeb736TYfrhBcji4i9OOiQV3jwlrmqeOQyddgrCUB6TEDPJfO6XGqxWSl56CxvbqSSZ3ugplptAoObUHuxJs5P6pMGvC03D5nDq3pSKajAgTix6xjM6Z4LKFHPx accanto@blacktower"
