---
- name: Install Lifecycle Transition
  hosts: resource
  gather_facts: False
  become: true

  tasks:
  - name: pause
    shell: python --version

  - name: set result
    set_fact:
      output__sg: "hello3"
