heat_template_version: "2018-08-31"
description: "Infrastructure for voice gateway"

parameters:
  instance_name:
    type: string
    label: Instance Name
    description: Name of resource instance
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  mgmt_network_id:
    type: string
    label: Mgmt Network id
    description: Type of instance (flavor) to be used
  mgmt_secgroup_id:
    type: string
    label: Mgmt Security Group
    description: Type of instance (flavor) to be used
  voice_network_id:
    type: string
    label: Voice Network id
    description: Type of instance (flavor) to be used
  voice_secgroup_id:
    type: string
    label: Voice Security Group id
    description: Type of instance (flavor) to be used
  internal_secgroup_id :
    type: string
    label: Internal  Security Group id
  internal_network_id:
    type: string
    label: Internal Network id

resources:

  mgmt_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      security_groups: 
        - { get_param: mgmt_secgroup_id }
      name: { get_param: instance_name }
      network: { get_param: mgmt_network_id }

  voice_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      security_groups: 
        - { get_param: voice_secgroup_id }
      name: { get_param: instance_name }
      network: { get_param: voice_network_id }

  internal_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      security_groups: 
        - { get_param: internal_secgroup_id }
      name: { get_param: instance_name }
      network: { get_param: internal_network_id }

  gateway: 
    type: "OS::Nova::Server"
    properties: 
      networks: 
        - port: { get_resource: mgmt_port }
        - port: { get_resource: voice_port }
        - port: { get_resource: internal_port }
      name: { get_param: instance_name }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      config_drive: true
      user_data_format: RAW
      user_data: |
        #cloud-config
        manage_etc_hosts: true
        bootcmd:
         - [ sysctl, net.ipv4.ip_forward=1 ]
         - [ ip, link, set, ens4, up ]
         - [ dhclient, ens4 ]
         - [ sh, -c, echo "nameserver 8.8.8.8" > /etc/resolv.conf ]
        ssh_pwauth: True
        password: ubuntu
        chpasswd:
          list: |
            ubuntu:ubuntu
          expire: False
        package_update: false

outputs:
  mgmt_ip_address: 
    value: { get_attr: [ mgmt_port , fixed_ips, 0, ip_address ] }
  voice_ip_address:
    value: { get_attr: [ voice_port, fixed_ips, 0, ip_address ] }
  internal_ip_address:
    value: { get_attr: [ internal_port, fixed_ips, 0, ip_address ] }
