pipeline{
    agent any
    stages{
        stage('onboard ip-pbx'){
		    when {
                branch 'master'
            }
            steps{
				sh "lmctl env list"
				sh "lmctl project push testing"               
            }
        }
        stage('test ip-pbx'){
		    when {
                branch 'master'
            }
            steps{
                sh "lmctl project test testing"
            }
        }
        stage('package ip-pbx'){
		    when {
                branch 'master'
            }
            steps{
                sh "curl -v -u admin:admin123 --upload-file ./_lmctl/_build/ip-pbx-vnf-1.0.tgz http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/ip-pbx-vnf/"              
            }
        }
    }
}