pipeline{
    agent any
    stages{
        stage('onboard sip-performance'){
            steps{
				sh "lmctl env list"
				sh "lmctl project push testing"               
            }
        }
        stage('test sip-performance'){
            steps{
                sh "lmctl project test testing"
            }
        }
        stage('package sip-performance'){
            steps{
                sh "curl -v -u admin:admin123 --upload-file ./_lmctl/_build/sip-performance-1.0.tgz http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/sip-performance/"              
            }
        }
    }
}