---
- name: create the router instance
  os_router:
    state: present
    name: "{{ router_name }}"
    network: "{{ network }}"
    interfaces:
      - "{{ interface }}"
  register: router_stat
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ os_password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ os_projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ os_projectname }}"
    OS_USERNAME: "{{ os_username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- debug:
    var: router_stat

# - name: report INTERNAL_RESOURCE
#   debug:
#     msg:
#      - "routerid: {{ netid}}"
#      - "type: openstack-network"

- name: report PROPERTIES
  debug:
    msg:
      - "router_id: {{ router_stat.id}}"
