- name: add deployment location host to hosts inventory
  add_host:
     name: "dockerlocation"
     groups: deploymentLocations
     ansible_ssh_host: "{{ location_server }}"
     ansible_user: "{{ location_user }}"
     ansible_connection: ssh
     ansible_ssh_pass: "{{ location_pwd }}"
     ansible_sudo_pass: "{{ location_pwd }}"
    
- name: add container to hosts inventory
  when: mgmt_address is defined 
  add_host:
     name: "{{ instance_name }}"
     groups: voip
     ansible_user: ubuntu
     ansible_connection: ssh
     ansible_ssh_pass: ubuntu
     ansible_sudo_pass: "{{ location_pwd }}"
     ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyCommand='sshpass -p {{ location_pwd }} ssh -o StrictHostKeyChecking=no -W %h:%p {{ location_user }}@{{ location_server }}'"