heat_template_version: "2018-08-31"
description: "Base infrastructure for Confernce Demo using Jitsi"
resources:

  conf_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules:
        - port_range_min: 1
          port_range_max: 65535
          protocol: udp 
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: conf_security_group

  conf_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: conf_net

  conf_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: conf_net }
      name: conf_subnet
      enable_dhcp: true
      cidr: "10.0.1.0/24"

  internal_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules:
        - port_range_min: 1
          port_range_max: 65535
          protocol: udp 
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: internal_security_group

  internal_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: internal_net

  internal_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: internal_net }
      name: internal_subnet
      enable_dhcp: true
      cidr: "10.0.2.0/24"



outputs:
  conf_network_id: 
    value: { get_resource:  conf_net }
  conf_security_group_id: 
    value: { get_resource: conf_security_group }
  internal_cidr:
    value: {get_attr: [ internal_subnet, cidr ] } 
  internal_network_id: 
    value: { get_resource:  internal_net }
  internal_security_group_id: 
    value: { get_resource: internal_security_group }
