heat_template_version: "2018-08-31"
description: "Base infrastructure for Voice Demo"

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used

resources:
  mgmt_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules: 
        - port_range_min: 22
          port_range_max: 22
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: mgmt_security_group

  mgmt_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: mgmt_net

  mgmt_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: mgmt_net }
      name: mgmt_subnet
      enable_dhcp: true
      cidr: "10.0.0.0/24"
  mgmt_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      fixed_ips: 
        - subnet: { get_resource: mgmt_subnet }
      security_groups: 
        - { get_resource: mgmt_security_group }
      name: mgmt_port
      network: { get_resource: mgmt_net }


  voice_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules:
        - port_range_min: 1
          port_range_max: 65535
          protocol: udp 
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: voice_security_group

  voice_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: voice_net

  voice_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: voice_net }
      name: voice_subnet
      enable_dhcp: true
      cidr: "10.0.1.0/24"

  jumphost_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "public"
      port_id: { get_resource: mgmt_port }

  jumphost: 
    type: "OS::Nova::Server"
    properties: 
      networks: 
        - port: { get_resource: mgmt_port }
      name: jumphost
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      config_drive: true
      user_data_format: RAW
      user_data: |
        #cloud-config
        manage_etc_hosts: true
        bootcmd: 
         - [ sysctl, net.ipv4.ip_forward=1 ]
         - [ sh, -c, echo 'nameserver 8.8.8.8' > /etc/resolv.conf ]
        ssh_pwauth: True
        password: ubuntu
        chpasswd:
          list: |
            ubuntu:ubuntu
          expire: False
        packages:
         - python"

  mgmt_router: 
    type: "OS::Neutron::Router"
    properties: 
      admin_state_up: true
      name: mgmt_router
      external_gateway_info:
        network: "public"


  mgmt_routerinterface: 
    type: "OS::Neutron::RouterInterface"
    properties: 
      router: { get_resource: mgmt_router }
      subnet: { get_resource: mgmt_subnet }

outputs:
  jumphost_internal_ip: 
    value: { get_attr: [ jumphost , first_address ] }
  jumphost_public_ip: 
    value: { get_attr: [ jumphost_floating_ip , floating_ip_address ] }
  mgmt_network_id: 
    value: { get_resource: mgmt_net }
  mgmt_security_group_id: 
    value: { get_resource: mgmt_security_group }
  voice_network_id: 
    value: { get_resource:  voice_net }
  voice_security_group_id: 
    value: { get_resource: voice_security_group }
