heat_template_version: "2018-08-31"
description: "Infrastructure for pbx"

parameters:
  pbx_ssh_key_name:
    type: string
    label: PBX Server SSH Key Name
    description: Name of SSH key pair
  instance_name:
    type: string
    label: Instance Name
    description: Name of resource instance
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  mgmt_network_id:
    type: string
    label: Mgmt Network id
    description: Type of instance (flavor) to be used
  mgmt_secgroup_id:
    type: string
    label: Mgmt Security Group
    description: Type of instance (flavor) to be used
  voice_network_id:
    type: string
    label: Voice Network id
    description: Type of instance (flavor) to be used
  voice_secgroup_id:
    type: string
    label: Voice Security Group id
    description: Type of instance (flavor) to be used

resources:

  mgmt_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      security_groups: 
        - { get_param: mgmt_secgroup_id }
      name: { get_param: instance_name }
      network: { get_param: mgmt_network_id }

  voice_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      security_groups: 
        - { get_param: voice_secgroup_id }
      name: { get_param: instance_name }
      network: { get_param: voice_network_id }

  pbx: 
    type: "OS::Nova::Server"
    properties: 
      networks: 
        - port: { get_resource: mgmt_port }
        - port: { get_resource: voice_port }
      name: { get_param: instance_name }
      flavor: { get_param: flavor }
      key_name: { get_resource: pbx_ssh_key }
#      key_name: { get_param: key_name }
      image: { get_param: image_id }
      config_drive: true
      user_data_format: RAW
      user_data: |
        #cloud-config
        manage_etc_hosts: true
        bootcmd:
         - [ sysctl, net.ipv4.ip_forward=1 ]
         - [ ip, link, set, ens4, up ]
         - [ dhclient, ens4 ]
         - [ sh, -c, echo "nameserver 8.8.8.8" > /etc/resolv.conf ]
        ssh_pwauth: True
        password: ubuntu
        chpasswd:
          list: |
            ubuntu:ubuntu
          expire: False
        package_update: false

  pbx_ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: pbx_ssh_key_name }
      save_private_key: True

outputs:
  mgmt_ip_address: 
    value: { get_attr: [ mgmt_port , fixed_ips, 0, ip_address ] }
  voice_ip_address:
    value: { get_attr: [ voice_port, fixed_ips, 0, ip_address ] }
  pbx_ssh_key:
    constraints:
      - custom_constraint: nova.keypair
        description: Must name a public key (pair) known to Nova
    str_replace:
      template: |
        {
          "privateKey": "$private_key",
          "publicKey": "$public_key",
          "name": "$key_name"
        }
      params:
          $key_name: { get_param: [ pbx_ssh_key_name ] }
          $private_key: { get_attr: [ pbx_ssh_key, private_key ] }
          $public_key: { get_attr: [ pbx_ssh_key, public_key ] }
