tosca_definitions_version: tosca_simple_yaml_1_0

description: Basic example to deploy a single VM

# Custom type required to set "image" and "key_name" properties on Openstack Server.
# This is a recommended workaround by Openstack (https://docs.openstack.org/heat-translator/latest/usage.html)
node_types:
  accanto.nodes.K8sCompute:
    derived_from: tosca.nodes.Compute
    properties:
      image:
        type: string
      container_port:
        type: integer

  accanto.nodes.K8sStorage:
    derived_from: tosca.nodes.BlockStorage
    properties:
      size:
        type: integer
      class:
        type: string

  accanto.nodes.K8sNetwork:
    derived_from: tosca.nodes.Root
    properties:
      name:
        type: string
      bridge:
        type: string
      subnet:
        type: string
      range_start:
        type: string
      range_end:
        type: string
    attributes:
      address:
        type: string

topology_template:
  inputs:
    instancename:
      type: string
    docker_image:
      type: string
      default: accanto/ip-pbx:1.1
    storage_size:
      type: integer
      # in GB
      default: 1
    storage_class:
      type: string
      default: microk8s-hostpath

  node_templates:
    ippbx:
      type: accanto.nodes.K8sCompute
      capabilities:
        host:
          #Heat translator will try and find an Openstack "flavour" which matches the given properties
          properties:
            num_cpus: 2
            disk_size: 10 GB
            mem_size: 2 GB
      properties:
        image: { get_input: docker_image }
        container_port: 80
      requirements:
        - mgmt_network:
            capability: tosca.capabilities.Attachment
            node: mgmt_network
            relationship:
              type: tosca.relationships.ConnectsTo
        - voice_network:
            capability: tosca.capabilities.Attachment
            node: voice_network
            relationship:
              type: tosca.relationships.ConnectsTo

    mgmt_network:
      type: accanto.nodes.K8sNetwork
      properties:
        name: mgmt
        bridge: br-mgmt
        subnet: "10.0.30.0/24"
        range_start: "10.0.30.55"
        range_end: "10.0.30.100"

    internal_network:
      type: accanto.nodes.K8sNetwork
      properties:
        name: internal
        bridge: br-internal
        subnet: "10.0.20.0/24"
        range_start: "10.0.20.55"
        range_end: "10.0.20.100"

    voice_network:
      type: accanto.nodes.K8sNetwork
      properties:
        name: voice
        bridge: br-voice
        subnet: "10.0.10.0/24"
        range_start: "10.0.10.55"
        range_end: "10.0.10.100"

  outputs:
    mgmt_ip_address:
      description: The private IP address of ippbx
      value: { get_attribute: [mgmt_network, address] }
    voice_ip_address:
      description: The private IP address of ippbx
      value: { get_attribute: [voice_network, address] }
    output_private_key:
      description: The private SSH key of the VM
      value: "-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEA3Tz2mr7SZiAMfQyuvBjM9Oi..Z1BjP5CE/Wm/Rr500P
RK+Lh9x5eJPo5CAZ3/ANBE0sTK0ZsDGMak2m1g7..3VHqIxFTz0Ta1d+NAj
wnLe4nOb7/eEJbDPkk05ShhBrJGBKKxb8n104o/..PdzbFMIyNjJzBM2o5y
5A13wiLitEO7nco2WfyYkQzaxCw0AwzlkVHiIyC..71pSzkv6sv+4IDMbT/
XpCo8L6wTarzrywnQsh+etLD6FtTjYbbrvZ8RQM..Hg2qxraAV++HNBYmNW
s0duEdjUbJK+ZarypXI9TtnS4o1Ckj7POfljiQI..IBAFyidxtqRQyv5KrD
kbJ+q+rsJxQlaipn2M4lGuQJEfIxELFDyd3XpxP..Un/82NZNXlPmRIopXs
2T91jiLZEUKQw+n73j26adTbteuEaPGSrTZxBLR..yssO0wWomUyILqVeti
6AkL0NJAuKcucHGqWVgUIa4g1haE0ilcm6dWUDo..fd+PpzdCJf1s4NdUWK
YV2GJcutGQb+jqT5DTUqAgST7N8M28rwjK6nVMI..BUpP0xpPnuYDyPOw6x
4hBt8DZQYyduzIXBXRBKNiNdv8fum68/5klHxp6..4HRkMUL958UVeljUsT
BFQlO9UCgYEA/VqzXVzlz8K36VSTMPEhB5zBATV..PRiXtYK1YpYV4/jSUj
vvT4hP8uoYNC+BlEMi98LtnxZIh0V4rqHDsScAq..VyeSLH0loKMZgpwFEm
bEIDnEOD0nKrfT/9K9sPYgvB43wsLEtUujaYw3W..Liy0WKmB8CgYEA34xn
1QlOOhHBn9Z8qYjoDYhvcj+a89tD9eMPhesfQFw..rsfGcXIonFmWdVygbe
6Doihc+GIYIq/QP4jgMksE1ADvczJSke92ZfE2i..fitBpQERNJO0BlabfP
ALs5NssKNmLkWS2U2BHCbv4DzDXwiQB37KPOL1c..kBHfF2/htIs20d1UVL
+PK+aXKwguI6bxLGZ3of0UH+mGsSl0mkp7kYZCm..OTQtfeRqP8rDSC7DgA
kHc5ajYqh04AzNFaxjRo+M3IGICUaOdKnXd0Fda..QwfoaX4QlRTgLqb7AN
ZTzM9WbmnYoXrx17kZlT3lsCgYEAm757XI3WJVj..WoLj1+v48WyoxZpcai
uv9bT4Cj+lXRS+gdKHK+SH7J3x2CRHVS+WH/SVC..DxuybvebDoT0TkKiCj
BWQaGzCaJqZa+POHK0klvS+9ln0/6k539p95tfX..X4TCzbVG6+gJiX0ysz
Yfehn5MCgYEAkMiKuWHCsVyCab3RUf6XA9gd3qY..fCTIGtS1tR5PgFIV+G
engiVoWc/hkj8SBHZz1n1xLN7KDf8ySU06MDggB..hJ+gXJKy+gf3mF5Kmj
DtkpjGHQzPF6vOe907y5NQLvVFGXUq/FIJZxB8k..fJdHEm2M4=
-----END RSA PRIVATE KEY-----"

