# Install playbooks for a network VNFC

---
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: create a new network instance
  hosts: "{{ 'localhost' if vimtype=='openstack' else 'dockerlocation' }}"
  gather_facts: False
  become: true    
  roles:
    - { role: create_instance }


    