---

- name: get deployment location_server
  hosts: localhost
  gather_facts: False
  roles:
    - { role: get_instance }

- name: create instance
  hosts: localhost
  gather_facts: False
  become: true
    
  roles:
    - { role: create_instance }


    