---
- name: create inventory
  hosts: localhost
  gather_facts: False
  become: true
  roles:
    - { role: create_inventory }

- name: delete network instance
  hosts: "{{ 'localhost' if vimtype=='openstack' else 'dockerlocation' }}"
  gather_facts: False
  become: true    
  roles:
    - { role: delete_instance }