---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ instance_name }}"
  annotations:
    k8s.v1.cni.cncf.io/networks: "{{ mgmt_network }},{{ internal_network }},{{ external_network }}"
spec:
  containers:
  - name: "{{ instance_name }}"
    image: accanto/kamailio:1.0
