---
- name: Check network exists
  os_networks_facts:
    name: "{{ networkname }}"
  register: net_info

- debug:
    var: net_info

- fail:
    msg: "A network with the name {{ networkname }} already exists." 
  when: net_info['ansible_facts']['openstack_networks'][0] is defined

- name: create network
  os_network:
    state: present
    name: "{{ networkname }}"
  when: provider_network is not defined or not( provider_network | default(false) | bool)

- name: create openstack provider network
  os_network:
    state: present
    name: "{{ networkname }}"
    provider_network_type: "{{ provider_network_type }}"
    provider_physical_network: "{{ provider_physical_network }}"
    provider_segmentation_id: "{{ provider_segmentation_id }}"
  when: provider_network is defined and provider_network | bool

- name: Check network exists
  os_networks_facts:
    name: "{{ networkname }}"
  register: net_info

- debug:
    var: net_info

- set_fact:
    netid: "{{ net_info['ansible_facts']['openstack_networks'][0].id}}"

- debug:
    var: netid

- name: create subnet
  os_subnet:
    state: present
    network_name: "{{ networkname }}" 
    name: "{{ networkname }}_subnet"
    cidr: "{{ subnet }}"
  register: subnet_result

- debug:
    var: subnet_result

- set_fact:
    subid: "{{ subnet_result['subnet']['id'] }}"

- debug:
    var: subid

- name: report PROPERTIES
  debug:
    msg:
      - "networkid: {{ netid}}"
      - "subnetid: {{ subid }}"
