---
- name: create network
  os_network:
    state: present
    name: "{{ networkname }}"
  when: not( provider_network | default(false) | bool)
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ projectname }}"
    OS_USERNAME: "{{ username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: create openstack provider network
  os_network:
    state: present
    name: "{{ networkname }}"
    provider_network_type: "{{ provider_network_type }}"
    provider_physical_network: "{{ provider_physical_network }}"
    provider_segmentation_id: "{{ provider_segmentation_id }}"
  when: provider_network | bool
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ projectname }}"
    OS_USERNAME: "{{ username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- name: Check network exists
  os_networks_facts:
    name: "{{ networkname }}"
  register: net_info
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ projectname }}"
    OS_USERNAME: "{{ username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"   

- debug:
    var: net_info

- set_fact:
    netid: "{{ net_info['ansible_facts']['openstack_networks'][0].id}}"

- debug:
    var: netid

- name: create subnet
  os_subnet:
    state: present
    network_name: "{{ networkname }}" 
    name: "{{ networkname }}_subnet"
    cidr: "{{ subnet }}"
  register: subnet_result
  environment: 
    OS_AUTH_TYPE: "password"
    OS_AUTH_URL: "{{ auth_url }}"
    OS_CACERT: ""
    OS_IDENTITY_API_VERSION: "3"
    OS_PASSWORD: "{{ password }}"
    OS_PROJECT_DOMAIN_ID: "default"
    OS_PROJECT_NAME: "{{ projectname }}"
    OS_REGION_NAME: "RegionOne"
    OS_TENANT_NAME: "{{ projectname }}"
    OS_USERNAME: "{{ username }}"
    OS_USER_DOMAIN_ID: "default"
    OS_VOLUME_API_VERSION: "3"

- name: report INTERNAL_RESOURCE
  debug:
    msg:
     - "id: {{ netid}}"
     - "type: opemnstack-network"

- name: report PROPERTIES
  debug:
    msg:
      - "networkid: {{ netid}}"
