---  
- name:  Lifecycle Operation
  hosts: localhost
  gather_facts: False
  tasks:  
    - name:  Lifecycle Operation
      debug:
        msg:
          "DEBUG: Integrity Lifecycle Operation"