heat_template_version: "2018-08-31"
description: "Base infrastructure for vpn network service"


resources:

  mgmt_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules: 
        - port_range_min: 22
          port_range_max: 22
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: mgmt_security_group

  mgmt_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: mgmt_net

  mgmt_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: mgmt_net }
      name: mgmt_subnet
      enable_dhcp: true
      cidr: "10.0.0.0/24"

  internal_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: internal_net

  internal_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: internal_net }
      name: internal_subnet
      enable_dhcp: true
      cidr: "10.0.10.0/24"

  external_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: external_net

  external_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: external_net }
      name: internal_subnet
      enable_dhcp: true
      cidr: "10.0.20.0/24"

  external_router: 
    type: "OS::Neutron::Router"
    properties: 
      admin_state_up: true
      name: internal_router
      external_gateway_info:
        network: "public"

  external_routerinterface: 
    type: "OS::Neutron::RouterInterface"
    properties: 
      router: { get_resource: external_router }
      subnet: { get_resource: external_subnet }

outputs:
  internal_network_id: 
    value: { get_resource: internal_net }
  external_network_id: 
    value: { get_resource:  external_net }
  mgmt_network_id: 
    value: { get_resource: mgmt_net }
  mgmt_secgroup_id: 
    value: { get_resource: mgmt_security_group }