---


- name: Add to Dispatch List
  hosts: resource
  gather_facts: False
  become: true

  vars:
    host_ip: "{{ properties.ipaddr }}"
    host_port: "{{ properties.port }}"
    dispatch_list_template: "{{ lookup('file', 'config/dispatcher.list.template') }}"
    lock_file_path: "/tmp/kamailio.lock"
    
  pre_tasks:      
   - wait_for:
       path: "{{ lock_file_path }}"
       state: absent  
      
   - name: create lock file 
     file:
       path: "{{ lock_file_path }}" 
       state: touch
       
  post_tasks:
   - name: delete lock file 
     file: 
       path: "{{ lock_file_path }}" 
       state: absent
       
  tasks:
    - name: update dispatch list
      block:      
      - name: add entry to dispatch list file  
        lineinfile:
          path: /usr/local/etc/kamailio/dispatcher.list
          create: yes
          line: "1 sip:{{ host_ip }}:{{ host_port }}"
          state: present
      - name: reload dispatch list
        shell: /usr/local/sbin/kamcmd dispatcher.reload 
      always:
        - name: delete lock file 
          file: 
            path: "{{ lock_file_path }}" 
            state: absent