---


- name: Remove from Dispatch List
  hosts: resource
  gather_facts: False
  become: true

  vars:
    host_ip: "{{ properties.ipaddr }}"
    host_port: "{{ properties.port }}"
    dispatch_list_template: "{{ lookup('file', 'config/dispatcher.list.template') }}"
    lock_file_path: "/tmp/kamailio.lock"
    
  pre_tasks:      
   - wait_for:
       path: "{{ lock_file_path }}"
       state: absent  
      
   - name: create lock file 
     file:
       path: "{{ lock_file_path }}" 
       state: touch
       
  post_tasks:
   - name: delete lock file 
     file: 
       path: "{{ lock_file_path }}" 
       state: absent
           
  tasks:
    - name: update dispatch list
      lineinfile:
        path: /usr/local/etc/kamailio/dispatcher.list
        line: "1 sip: {{ host_ip }}:{{ host_port }}"
        state: absent

    # - name: get current dispatcher.list
    #   shell: cat /usr/local/etc/kamailio/dispatcher.list
    #   register: dispatcher_list_current
      
    # - name: Run Python script to create new dispatch list
    #   become: false
    #   local_action: shell python config/deleteFromDispatchList.py "{{ dispatch_list_template }}" "{{dispatcher_list_current.stdout}}" "{{ host_ip }}" "{{ host_port }}"
    #   register: raw_dispatch_list_new 
    
    # - set_fact:
    #     dispatch_list_new : "{{ raw_dispatch_list_new.stdout_lines }}"
     
    # - name: write new kamailio dispatcher.list
    #   template:
    #     src: config/dispatcher.list.template
    #     dest: /usr/local/etc/kamailio/dispatcher.list     
    
    # - name: new dispatch list
    #   debug: msg={{ dispatch_list_new }}  

    - name: reload Kamailio
      shell: /usr/local/sbin/kamcmd dispatcher.reload        