---
- name: Install
  hosts: resource
  gather_facts: False
  become: true
  tasks:
    - name: If needed, install Python
      raw: apt-get update && apt-get -y install python3

    - name: Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
      raw: systemctl disable --now {{item}}
      with_items:
        - 'apt-daily.timer'
        - 'apt-daily-upgrade.timer'
      

    - name: Reload systemctl daemon to apply the new changes
      raw: systemctl daemon-reload
      

    - name: Wait for unattended upgrade to finish
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
      

    - name: Purge unattended upgrades
      raw: apt-get -y purge unattended-upgrades   
      

    - name:  Add the Jitsi repository key
      apt_key:
        url: https://download.jitsi.org/jitsi-key.gpg.key
        state: present 

    - name: Create a sources.list.d file with the repository
      shell: "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"

    - name: install full jitsi meet
    
      shell: |
        apt-get update
        export DEBIAN_FRONTEND=noninteractive 
        debconf-set-selections <<< 'jitsi-videobridge jitsi-videobridge/jvb-hostname string {{ properties.public_ip }}';
        apt-get install -y jitsi-meet
      args:
        executable: /bin/bash

    # - name: install full jitsi meet
    
    #   shell: |
    #     apt-get update
    #     export DEBIAN_FRONTEND=noninteractive 
    #     debconf-set-selections <<< 'jitsi-meet-prosody jitsi-meet/jvb-hostname string {{ properties.public_ip }}';
    #     debconf-set-selections <<< 'jitsi-meet jitsi-meet/jvb-hostname string {{ properties.public_ip }}';
    #     debconf-set-selections <<< 'jitsi-meet-prosody jitsi-meet-prosody/jvb-hostname string {{ properties.public_ip }}';
    #     debconf-set-selections <<< 'jitsi-meet jitsi-meet-prosody/jvb-hostname string {{ properties.public_ip }}';
    #     apt-get install -y jitsi-meet
    #   args:
    #     executable: /bin/bash
