---
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: Configure Lifecycle Transition
  hosts: "{{ instance_name }}"
  gather_facts: False
  become: true

  tasks:

  - name: copy restart.sh
    copy:
      src: ./config/restart.sh
      dest: /tmp
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755
  
  - name: copy myuac.xml
    copy:
      src: ./config/myuac.xml
      dest: /

  - name: create pythonmonitor
    file: 
      path: /pythonmonitor
      state: directory

  - name: copy monitor.py
    template:
      src: ./config/monitor.py
      dest: /pythonmonitor

  - name: create /etc/collectd
    file: 
      path: /etc/collectd
      state: directory

  - name: copy collectd.conf
    template:
      src: ./config/collectd.conf
      dest: /etc/collectd/

  - name: add kafka.lm to hosts
    become: yes
    shell: "echo {{ almip }} kafka.lm >> /etc/hosts"
