---
- name: create inventory
  hosts: localhost
  gather_facts: False
  roles:
    - { role: create_inventory }

- name: delete instance
  hosts: "localhost"
  gather_facts: False
  become: true
  roles:
    - { role: delete_instance }