---
- name: Check network exists
  os_networks_facts:
    name: "{{ networkname }}"
  register: net_info

- debug:
    var: net_info

#- fail:
#    msg: "A network with the name {{ networkname }} already exists." 
#  when: net_info['ansible_facts']['openstack_networks'][0] is defined

- name: create network
  os_network:
    state: present
    name: "{{ networkname }}"

- name: Check network exists
  os_networks_facts:
    name: "{{ networkname }}"
  register: net_info

- debug:
    var: net_info

- set_fact:
    netid: "{{ net_info['ansible_facts']['openstack_networks'][0].id}}"

- debug:
    var: netid

- name: create subnet
  os_subnet:
    state: present
    network_name: "{{ networkname }}" 
    name: "{{ networkname }}_subnet"
    cidr: "{{ subnet }}"
  register: subnet_result

- debug:
    var: subnet_result

- set_fact:
    subid: "{{ subnet_result['subnet']['id'] }}"

- debug:
    var: subid

- name: report PROPERTIES
  debug:
    msg:
      - "networkid: {{ netid}}"
      - "subnetid: {{ subid }}"
