---
- name: "Remove gateway instance {{ instance_name }}"
  os_server:
    state: absent
    name: "{{ instance_name }}"
  register: server_result

- name: remove internal port
  os_port:
    state: absent
    name: "internal_port-{{ instance_name }}"

- name: remove external port
  os_port:
    state: absent
    name: "external_port-{{ instance_name }}"

- name: remove mgmt port
  os_port:
    state: absent
    name: "mgmt_port-{{ instance_name }}"
    
- name: "remove mgmt security group for {{ instance_name }}"
  os_security_group:
    state: absent
    name: "{{ instance_name }}-mgmt-sec"

- name: "remove voip security group for {{ instance_name }}"
  os_security_group:
    state: absent
    name: "{{ instance_name }}-voip-sec"
