---

- name: Install Lifecycle Operation
  hosts: localhost
  gather_facts: False
  
  tasks:
   - name: report INTERNAL_PROPERTIES
     debug:
       msg:
         - "instance_id: {{ instanceid }}"
      
  
